"""Committed board artifacts for the survivor planner (#72).

The JSON here is generated by ``scripts/build_survivor_board.py`` and
checked in on purpose: the deployed API needs the forward schedule and
power ratings, and can reach neither nflverse nor polars. Stdlib only in
this package, so the API can import it.
"""

from pathlib import Path

DIR = Path(__file__).parent


def board_path(season: int) -> Path:
    return DIR / f"survivor_board_{season}.json"


def built_seasons() -> list[int]:
    """Seasons with a committed artifact, ascending."""
    return sorted(
        int(p.stem.rsplit("_", 1)[1]) for p in DIR.glob("survivor_board_*.json")
    )
